### Test root endpoint
GET http://localhost:7070/api/

###

### Get all candidates
GET http://localhost:7070/api/candidates
Authorization: Bearer {{token}}

###

### Get single candidate by ID
GET http://localhost:7070/api/candidates/1
Authorization: Bearer {{token}}


### Populate database med testdata
GET http://localhost:7070/api/populate


### Link skill til candidate (ADMIN)
PUT http://localhost:7070/api/candidates/1/skills/2
Authorization: Bearer {{token}}


### Create single candidate (ADMIN)
POST http://localhost:7070/api/candidates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alice Andersen",
  "phone": "88889999",
  "education": "BSc Software Development"
}


###

### Create multiple candidates (array) kræver controller.create understøtter array
### Candidate 1
POST http://localhost:7070/api/candidates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Jonas Jensen",
  "phone": "22223333",
  "education": "AP Computer Science"
}

### Candidate 2
POST http://localhost:7070/api/candidates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Maja Madsen",
  "phone": "44445555",
  "education": "BSc Software Development"
}




###

### Update candidate by ID
PUT http://localhost:7070/api/candidates/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alice A.",
  "phone": "88889999",
  "education": "BSc Software Development"
}



###
@url = http://localhost:7070/api
@token = {{token}}
### Delete candidate by ID
DELETE http://localhost:7070/api/candidates/1
Authorization: Bearer {{token}}


###
GET http://localhost:7070/api/



### User ###


############################ Register
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "thomas",
  "password": "test123",
  "address": "Testvej 1",
  "phone": "12345678"
}

###

POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "username": "Mie",
  "password": "1234"
}




> {%
    client.global.set("token", response.body.token);
%}

###

### Create candidate (ADMIN)
POST {{url}}/candidates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alice A.",
  "phone": "88889999",
  "education": "BSc Software Development"
}


###

### Get all candidates
GET {{url}}/candidates
Authorization: Bearer {{token}}

###

### Delete candidate
DELETE {{url}}/candidates/1
Authorization: Bearer {{token}}
